name: "run ci"
on:
  push:
    branches:
    - main
jobs:
  lint:
    name: "Run ESLint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn run lint
  
  bundle:
    name: "Bundle distribution"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn run generate
      - run: yarn run compile
      - run: yarn run bundle